#!/usr/bin/env bash
GOPATH=~/go
echo ===set scope $SOUL
if [ "seed.sl" -nt "seed.sl.go" ]; then
		node ../soul/bootstrap.sl.js seed.sl 3
		echo ===gen done
fi
if [ "progl-grammar.js" -nt "progl-parser.js" ]; then
		node progl-grammar.js
		echo ===gen progl parser
fi
if [ "tpl-grammar.js" -nt "tpl-parser.js" ]; then
		node tpl-grammar.js
		echo ===gen tpl parser				
fi

rc=$?
if [[ $rc != 0 ]]; then
		echo ===build failed
		exit 1
fi

if [ -z "$1" ]; then
		for f in `ls test/0*.sl `
		do
				res=$(/usr/bin/go run seed.sl.go $f $SOUL | diff ${f}.log$SOUL -)
				if [[ $res ]]; then
						echo ===error: $f
						echo $res
				fi			 
				rc=$?
				if [[ $rc == 0 ]]; then
						echo ===done: $f 
				fi
		done
else
	  if [ "seed.sl.go" -nt "soul2" ]; then
				/usr/bin/go build
		fi		
		for f in `ls test/$1*.sl `
		do
 				./soul2 $f $SOUL | tee ${f}.log$SOUL
				rc=$?
				if [[ $rc == 0 ]]; then
						echo ===done: $f 
				fi
		done
fi
echo ===all done
