#!/usr/bin/env bash
GOPATH=~/go
node ../soul/bootstrap.sl.js seed.sl 3
rc=$?
if [[ $rc != 0 ]]; then
		echo ===build failed
		exit 1
fi

for f in `ls test/basic/* `
do
	/usr/bin/go run seed.sl.go $f
  rc=$?
	if [[ $rc == 0 ]]; then
			echo ===exec done: $f 
	fi
done
