#!/usr/bin/env node
var p = require("./progl-parser");
var t = require("./tpl-parser");
var g = require("./get-stdin");
var fs = require("fs")
function x(str){
	var s = t.parse(str);
	return p.parse(s) 
}
if(!process.argv[2]){
  g().then(str => {		
  	console.log(JSON.stringify(x(str)))
	});
}else{
	var str = fs.readFileSync(process.argv[2]).toString()
  console.log(JSON.stringify(x(str)))	
}
